### ISSUE TITLE
Can you check the compatibility of different versions of mmcv ?

### ISSUE THREAD

**Issue by Dosin-Lee** [RockeyCoss/Prompt-Segment-Anything#4]
Thank you for your amazing work.
I already test the demo on huggingface.

However, I have some issues. 
Following your instructions, I get an error with "from mmcv import Config" in the Evaluate Metrics step and Gradio Demo.

Below are the results of checking the version when the command line uploaded on GitHub is installed.
`pip show mmdet | grep Version` : Version: 3.0.0
`pip show mmcv |grep Version` :  Version: 2.0.0

If i downgrade to mmcv-full 1.7.1 instead of mmcv(v2.0.0), it allows the Gradio Demo to work and generate a URL, 
but the Evaluate Metrics still doesn't work.

**Comment by RockeyCoss** [comment]
I would like to apologize for providing incorrect version information in the README and thank you for pointing out this issue. After checking my environment, I found that the correct version for mmcv-full should be less than 3.0.0 and there is no need to install the mmdet package. 

You can refer to the latest README to install the environment. Thank you again for bringing this to my attention.

**Comment by Dosin-Lee** [comment]
Im still stuck 
Even if this bothers you... I need your help. 


```
#Command
mim install "mmcv<2.0.0"
pip install -r requirements.txt
cd projects/instance_segment_anything/ops
python setup.py build install
cd ../../..
export PYTHONPATH=$(pwd)
python tools/test.py /workspace/Instance-Segment-Anything/projects/configs/focalnet_dino/focalnet-l-dino_sam-vit-h.py --eval segm
python app.py
```

```
#Error
/opt/conda/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
Traceback (most recent call last):
  File "app.py", line 40, in <module>
    from mmcv.ops import RoIPool
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/opt/conda/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```


#additional check
`pip show mmcv |grep Version` :Version: 1.7.1

**Comment by RockeyCoss** [comment]
My apology again. The corrent command should be ``mim install "mmcv-full<2.0.0"`` instead of ``mim install "mmcv<2.0.0"``

**Comment by Dosin-Lee** [comment]
Thank you for your help.
I used the following command and was able to successfully run app.py.


```
git clone https://github.com/RockeyCoss/Instance-Segment-Anything
cd Instance-Segment-Anything
pip install torch torchvision
pip install -U openmim
mim install "mmcv-full<2.0.0"
pip install -r requirements.txt
cd projects/instance_segment_anything/ops
python setup.py build install
cd ../../..
pip install gradio
python app.py

```

`pip show mmcv | grep Version` #Version: 1.5.0


---------------------------------------------

I am facing another issue during Evaluate Metrics.

It seems like mmdet is not being recognized due to some problem.


```
#Command
python tools/test.py /workspace/Instance-Segment-Anything/projects/configs/focalnet_dino/focalnet-l-dino_sam-vit-h.py --eval segm
```


#Error
Traceback (most recent call last):
  File "tools/test.py", line 15, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
ModuleNotFoundError: No module named 'mmdet





----------------------------------------------

After using [pip install mmdet] , There seems to be an error again related to the version problem of mmcv.


```
#Command
python tools/test.py /workspace/Instance-Segment-Anything/projects/configs/focalnet_dino/focalnet-l-dino_sam-vit-h.py --eval segm
```


#Error
Traceback (most recent call last):
  File "tools/test.py", line 15, in <module>
    from mmdet.apis import multi_gpu_test, single_gpu_test
  File "/opt/conda/lib/python3.8/site-packages/mmdet/__init__.py", line 16, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.5.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

**Comment by RockeyCoss** [comment]
That's weird...Have you attempted to run ``export PYTHONPATH=$(pwd)`` before executing ``python tools/test.py /workspace/Instance-Segment-Anything/projects/configs/focalnet_dino/focalnet-l-dino_sam-vit-h.py --eval segm``?

**Comment by Dosin-Lee** [comment]
Hi@

I just open a new Docker, and all the issues have been resolved.

It seems that there were problems during the repeated installation process.

Thank you for your advices and help.

Your performance in the end was fantastic.

I hope that even greater things happen in the near future.

Thanks.

**Comment by RockeyCoss** [comment]
> greater

Glad to hear that! It's encouraging to know that our efforts have been successful.

**Comment by RockeyCoss** [comment]
> Hi@
> 
> I just open a new Docker, and all the issues have been resolved.
> 
> It seems that there were problems during the repeated installation process.
> 
> Thank you for your advices and help.
> 
> Your performance in the end was fantastic.
> 
> I hope that even greater things happen in the near future.
> 
> Thanks.

Glad to hear that! It's encouraging to know that our efforts have been successful.
Thank you for pointing out the problem again!
